swagger: "2.0"
info:
  version: "0.0.1"
  title: Product Service App
# during dev, should point to your local machine
host: 1fv92h0tcf.execute-api.eu-west-1.amazonaws.com
# basePath prefixes all resource paths 
basePath: /dev
# 
schemes:
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /products:
    # binds a127 app logic to a route
    x-swagger-router-controller: get-all-products
    get:
      description: Returns products list to the caller
      # used as the method name of the controller
      operationId: get-all-products
      responses:
        "200":
          description: Success
          schema:
            type: array
            $ref: "#/definitions/ProductResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /products/{id}:
    x-swagger-router-controller: get-product-by-id
    get:
      description: Get product by id
      operationId: get-product-by-id
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: String ID of the product to get
      responses:
        "200":
          description: Success
          schema:
            type: object
            $ref: "#/definitions/ProductResponse"
        "404":
          description: Not Found
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  ProductResponse:
    required:
      - id
      - count
      - title
      - price
    properties:
      count:
        type: number
      description:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
